// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntruxdpnwczdvrrqonko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cnV4ZHBud2N6ZHZycnFvbmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzczODIsImV4cCI6MjA3MDExMzM4Mn0.jVyEZT4m5Y9mdVfFO-45b1cUUvq6m_1xz83Xs-nqGEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});